name: Hello, World!
description: Greet someone and record the time
author: GitHub Actions

# Define your inputs here.
inputs:
  hosts:
    description: All hosts
    required: true
  production-hosts:
    description: Target hosts
    required: true
outputs:
  time:
    description: The time we greeted you

runs:
  using: node20
  main: dist/index.js
