name: Hello, World!
description: Greet someone and record the time
author: GitHub Actions

# Define your inputs here.
inputs:
  production-hosts:
    description: Target hosts
    required: true
  staging-hosts:
    description: Staging hosts
    required: true
  host:
    description: Host to deploy to
    required: true
outputs:
  matrix:
    description: Deployemnet matrix
  branch:
    description: Branch name
  host:
    description: Host to deploy to

runs:
  using: node20
  main: dist/index.js
